//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnameh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Karnameh
    {
        public tbl_Karnameh()
        {
            this.tbl_Marks = new HashSet<tbl_Marks>();
        }
    
        public long id { get; set; }
        public string Student_id_FK { get; set; }
        public string Avarage { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Years_id_FK { get; set; }
        public Nullable<long> MoavenEjraei_id_FK { get; set; }
        public string DateSabt { get; set; }
        public Nullable<bool> IsRespect { get; set; }
        public Nullable<int> Nobat { get; set; }
        public Nullable<bool> IsOk { get; set; }
    
        public virtual tbl_MoaveninEjraei tbl_MoaveninEjraei { get; set; }
        public virtual tbl_Students tbl_Students { get; set; }
        public virtual tbl_Years tbl_Years { get; set; }
        public virtual ICollection<tbl_Marks> tbl_Marks { get; set; }
    }
}
