//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnameh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TosifAmalkard
    {
        public tbl_TosifAmalkard()
        {
            this.tbl_Payeh = new HashSet<tbl_Payeh>();
            this.tbl_Marks = new HashSet<tbl_Marks>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<int> MaxMark { get; set; }
    
        public virtual ICollection<tbl_Payeh> tbl_Payeh { get; set; }
        public virtual ICollection<tbl_Marks> tbl_Marks { get; set; }
    }
}
