//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnameh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Years
    {
        public tbl_Years()
        {
            this.tbl_StudentClasses = new HashSet<tbl_StudentClasses>();
            this.tbl_Marks = new HashSet<tbl_Marks>();
            this.tbl_Karnameh = new HashSet<tbl_Karnameh>();
        }
    
        public int id { get; set; }
        public string Years { get; set; }
    
        public virtual ICollection<tbl_StudentClasses> tbl_StudentClasses { get; set; }
        public virtual ICollection<tbl_Marks> tbl_Marks { get; set; }
        public virtual ICollection<tbl_Karnameh> tbl_Karnameh { get; set; }
    }
}
