//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnameh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Students
    {
        public tbl_Students()
        {
            this.tbl_StudentClasses = new HashSet<tbl_StudentClasses>();
            this.tbl_Marks = new HashSet<tbl_Marks>();
            this.tbl_Karnameh = new HashSet<tbl_Karnameh>();
        }
    
        public string CodeMelli { get; set; }
        public string Name { get; set; }
        public string Lname { get; set; }
        public string Fname { get; set; }
        public string BirthDate { get; set; }
        public Nullable<long> Class_id_FK { get; set; }
        public Nullable<long> Schools_id_FK { get; set; }
        public Nullable<int> Payeh_id_FK { get; set; }
        public string Pic { get; set; }
    
        public virtual tbl_Classes tbl_Classes { get; set; }
        public virtual tbl_Payeh tbl_Payeh { get; set; }
        public virtual tbl_Schools tbl_Schools { get; set; }
        public virtual ICollection<tbl_StudentClasses> tbl_StudentClasses { get; set; }
        public virtual ICollection<tbl_Marks> tbl_Marks { get; set; }
        public virtual ICollection<tbl_Karnameh> tbl_Karnameh { get; set; }
    }
}
