//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnameh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Classes
    {
        public tbl_Classes()
        {
            this.tbl_StudentClasses = new HashSet<tbl_StudentClasses>();
            this.tbl_Students = new HashSet<tbl_Students>();
        }
    
        public long id { get; set; }
        public string Name { get; set; }
        public Nullable<long> Teachers_PersonalCode_FK { get; set; }
        public Nullable<long> School_id_FK { get; set; }
        public Nullable<int> Payeh_id_FK { get; set; }
    
        public virtual tbl_Payeh tbl_Payeh { get; set; }
        public virtual tbl_Schools tbl_Schools { get; set; }
        public virtual tbl_Teachers tbl_Teachers { get; set; }
        public virtual ICollection<tbl_StudentClasses> tbl_StudentClasses { get; set; }
        public virtual ICollection<tbl_Students> tbl_Students { get; set; }
    }
}
