//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnameh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Marks
    {
        public int id { get; set; }
        public Nullable<int> Payeh_id_FK { get; set; }
        public string Student_id_FK { get; set; }
        public Nullable<long> Lesson_id_FK { get; set; }
        public Nullable<int> Years_id_FK { get; set; }
        public Nullable<double> Mark { get; set; }
        public Nullable<int> TosifAmalkard_id_FK { get; set; }
        public Nullable<long> Karnameh_id_FK { get; set; }
        public Nullable<int> Nobat { get; set; }
    
        public virtual tbl_Lessons tbl_Lessons { get; set; }
        public virtual tbl_Students tbl_Students { get; set; }
        public virtual tbl_TosifAmalkard tbl_TosifAmalkard { get; set; }
        public virtual tbl_Years tbl_Years { get; set; }
        public virtual tbl_Karnameh tbl_Karnameh { get; set; }
    }
}
