//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnameh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Payeh
    {
        public tbl_Payeh()
        {
            this.tbl_Classes = new HashSet<tbl_Classes>();
            this.tbl_Lessons = new HashSet<tbl_Lessons>();
            this.tbl_Teachers = new HashSet<tbl_Teachers>();
            this.tbl_Students = new HashSet<tbl_Students>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> TosifAmalkard_id_FK { get; set; }
    
        public virtual ICollection<tbl_Classes> tbl_Classes { get; set; }
        public virtual ICollection<tbl_Lessons> tbl_Lessons { get; set; }
        public virtual tbl_TosifAmalkard tbl_TosifAmalkard { get; set; }
        public virtual ICollection<tbl_Teachers> tbl_Teachers { get; set; }
        public virtual ICollection<tbl_Students> tbl_Students { get; set; }
    }
}
