//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnameh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StudentClasses
    {
        public long id { get; set; }
        public string Student_id_FK { get; set; }
        public Nullable<long> Class_id_FK { get; set; }
        public Nullable<int> Years_id_K { get; set; }
    
        public virtual tbl_Years tbl_Years { get; set; }
        public virtual tbl_Classes tbl_Classes { get; set; }
        public virtual tbl_Students tbl_Students { get; set; }
    }
}
