//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnameh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Teachers
    {
        public tbl_Teachers()
        {
            this.tbl_Classes = new HashSet<tbl_Classes>();
        }
    
        public long PersonalCode { get; set; }
        public string CodeMelli { get; set; }
        public string Name { get; set; }
        public string Lname { get; set; }
        public string Fname { get; set; }
        public Nullable<int> Payeh_id_FK { get; set; }
        public Nullable<long> Schools_id_FK { get; set; }
    
        public virtual tbl_Schools tbl_Schools { get; set; }
        public virtual ICollection<tbl_Classes> tbl_Classes { get; set; }
        public virtual tbl_Payeh tbl_Payeh { get; set; }
    }
}
