//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnameh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MoaveninEjraei
    {
        public tbl_MoaveninEjraei()
        {
            this.tbl_Schools = new HashSet<tbl_Schools>();
            this.tbl_Karnameh = new HashSet<tbl_Karnameh>();
        }
    
        public long PersonalCode { get; set; }
        public string CodeMelli { get; set; }
        public string Name { get; set; }
        public string Lname { get; set; }
        public string Fname { get; set; }
        public string BirthDate { get; set; }
    
        public virtual ICollection<tbl_Schools> tbl_Schools { get; set; }
        public virtual ICollection<tbl_Karnameh> tbl_Karnameh { get; set; }
    }
}
