//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnameh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Schools
    {
        public tbl_Schools()
        {
            this.tbl_Teachers = new HashSet<tbl_Teachers>();
            this.tbl_Classes = new HashSet<tbl_Classes>();
            this.tbl_Students = new HashSet<tbl_Students>();
        }
    
        public long id { get; set; }
        public string Name { get; set; }
        public Nullable<long> Manager_PersonalCode_FK { get; set; }
        public Nullable<long> MoavenEjraei_PersonalCode_FK { get; set; }
        public string Password { get; set; }
    
        public virtual tbl_Managers tbl_Managers { get; set; }
        public virtual tbl_MoaveninEjraei tbl_MoaveninEjraei { get; set; }
        public virtual ICollection<tbl_Teachers> tbl_Teachers { get; set; }
        public virtual ICollection<tbl_Classes> tbl_Classes { get; set; }
        public virtual ICollection<tbl_Students> tbl_Students { get; set; }
    }
}
