//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnameh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viw_Classes
    {
        public long id { get; set; }
        public string Name { get; set; }
        public Nullable<long> Teachers_PersonalCode_FK { get; set; }
        public Nullable<long> School_id_FK { get; set; }
        public string SchoolsName { get; set; }
        public string TeachersName { get; set; }
        public string PayehName { get; set; }
    }
}
